### ISSUE TITLE
Hmm. Your browser version isn't supported

### ISSUE THREAD

**Issue by linascheryservers** [sportradar/ms-teams-linux#24]
Just today (12.12.2017) ms-teams-linux app refused to work with a funny message:
`Hmm. Your browser version isn't supported. Here's what works:`
`Microsoft Edge - Install for free`
`Google Chrome - Install for free`
`Mozilla Firefox - Install for free`

**Comment by linascheryservers** [comment]
Never mind, solved by myself. Need to build fresh one :)
For those, who looks for recipe:
`git clone https://github.com/sportradar/ms-teams-linux.git`
`cd ms-teams-linux`
modify  _ms-teams-linux/src/background.js_:
```
 mainWindow.webContents.setUserAgent(
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/**64**.0.2883.87 Safari/537.36'
  );
```

`npm install gulp-install gulp gulp-watch gulp-batch fs-jetpack rollup electron about-window electron-builder`
`npm run release`
`cd dist`
`./ms-teams-capsule-0.4.0-x86_64.AppImage`

**Comment by karmainside** [comment]
Hello, @linascheryservers. This fork is not maintained any more. Please to [the original project](https://github.com/karmainside/ms-teams-linux) for up-to-date version.
