### ISSUE TITLE
Links should open in a new tab of the default browser

### ISSUE THREAD

**Issue by vladas** [sportradar/ms-teams-linux#4]
At the moment links open in a new window of the app.

**Comment by miclud** [comment]
Agreed. This should be top priority

**Comment by vladas** [comment]
related discussion - https://github.com/electron/electron/issues/1344
and in particular this comment shows how this can be done: https://github.com/electron/electron/issues/1344#issuecomment-208839713

**Comment by vladas** [comment]
code example and docu: https://electron.atom.io/docs/api/web-contents/

**Comment by miclud** [comment]
Added stuff in #9. Running on that branch locally until it get's merged

**Comment by vladas** [comment]
Yay! Great stuff, Michelle!
